# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAmazonPriceFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_tax', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('fixed_margin', models.IntegerField()),
                ('minimum_margin', models.IntegerField()),
                ('paypal_fees_perc', models.IntegerField()),
                ('paypal_fees_fixed', models.IntegerField()),
                ('ebay_fees', models.IntegerField()),
                ('manual_override', models.IntegerField()),
            ],
        ),
    ]
