# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_ebaysellersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbaySellerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_id', models.CharField(default='', max_length=255)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('custom_label', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField()),
                ('no_of_times_sold', models.IntegerField()),
                ('date_of_listing', models.DateField()),
            ],
        ),
    ]
