# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_ebayselleritems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayselleritems',
            name='custom_label',
        ),
        migrations.RemoveField(
            model_name='ebayselleritems',
            name='id',
        ),
        migrations.AlterField(
            model_name='ebayselleritems',
            name='ebay_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
