# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20171111_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEbaySellerKeyset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=255)),
                ('appid', models.CharField(max_length=100)),
                ('devid', models.CharField(max_length=100)),
                ('certid', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
