# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_addebaysellerkeyset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayselleritems',
            name='custom_label',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ebayselleritems',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
