# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_remove_amazonrun_run_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayrundetails',
            name='cause_if_fail',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayrundetails',
            name='is_ebay_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amazonrundetails',
            name='is_ebay_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amazonrundetails',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
