# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20171115_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayselleritems',
            name='no_of_times_sold',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='ebayselleritems',
            name='quantity',
            field=models.IntegerField(default='-1'),
        ),
    ]
