# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_auto_20170924_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayamazonpriceformula',
            name='maximum_range',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayamazonpriceformula',
            name='minimum_range',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
