# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20171023_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonrundetails',
            name='proxy_used',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proxylog',
            name='proxy',
            field=models.CharField(max_length=50),
        ),
    ]
