# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEbaySellerKeyset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=255)),
                ('appid', models.CharField(max_length=100)),
                ('devid', models.CharField(max_length=100)),
                ('certid', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonRun',
            fields=[
                ('run_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('run_start_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonRunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default='', max_length=255)),
                ('group_id', models.CharField(default='', max_length=255)),
                ('amazon_url', models.CharField(default='', max_length=255)),
                ('scrape_time', models.DateTimeField(auto_now=True)),
                ('price_str', models.CharField(default='', max_length=20)),
                ('is_prime', models.BooleanField(default=False)),
                ('is_ebay_updated', models.BooleanField(default=False)),
                ('in_stock_str', models.CharField(default='', max_length=10)),
                ('proxy_used', models.CharField(default='', max_length=50)),
                ('ebay_id', models.CharField(default='', max_length=30)),
                ('is_eligible_for_ebay_update', models.BooleanField(default=True)),
                ('cause_if_fail', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EbayAmazonPriceFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_range', models.IntegerField()),
                ('maximum_range', models.IntegerField()),
                ('vendor_tax', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('fixed_margin', models.IntegerField()),
                ('minimum_margin', models.IntegerField()),
                ('paypal_fees_perc', models.IntegerField()),
                ('paypal_fees_fixed', models.IntegerField()),
                ('ebay_fees', models.IntegerField()),
                ('manual_override', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EbayProductsCsvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(default='', max_length=255)),
                ('vendor_url', models.CharField(default='', max_length=255)),
                ('vendor_variant', models.CharField(default='', max_length=255)),
                ('vendor_stock', models.CharField(default='', max_length=255)),
                ('vendor_price', models.CharField(default='', max_length=255)),
                ('vendor_shipping', models.CharField(default='', max_length=255)),
                ('reference', models.CharField(default='', max_length=255)),
                ('compare_url', models.CharField(default='', max_length=255)),
                ('compare_variant', models.CharField(default='', max_length=255)),
                ('compare_stock', models.CharField(default='', max_length=255)),
                ('compare_price', models.CharField(default='', max_length=255)),
                ('compare_shipping', models.CharField(default='', max_length=255)),
                ('profit_formula', models.CharField(default='', max_length=255)),
                ('selling_formula', models.CharField(default='', max_length=255)),
                ('reprice_store', models.CharField(default='', max_length=255)),
                ('reprice_sku', models.CharField(default='', max_length=255)),
                ('reprice_pause', models.CharField(default='', max_length=255)),
                ('sales_price', models.CharField(default='', max_length=255)),
                ('estimated_profit', models.CharField(default='', max_length=255)),
                ('autoCompare', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EbayRunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default='', max_length=255)),
                ('group_id', models.CharField(default='', max_length=255)),
                ('amazon_url', models.CharField(default='', max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('price_str', models.CharField(default='', max_length=20)),
                ('in_stock_str', models.CharField(default='', max_length=10)),
                ('ebay_price', models.CharField(default='', max_length=10)),
                ('ebay_stock', models.CharField(default='', max_length=10)),
                ('is_ebay_updated', models.BooleanField(default=False)),
                ('cause_if_fail', models.CharField(default='', max_length=255)),
                ('ebay_url', models.CharField(default='', max_length=255)),
                ('ebay_id', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EbaySellerItems',
            fields=[
                ('photo', models.CharField(default='', max_length=255)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('ebay_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('custom_label', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default='-1')),
                ('no_of_times_sold', models.IntegerField(default='-1')),
                ('date_of_listing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EbaySellerSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default='', max_length=255)),
                ('seller_id', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('price_str', models.CharField(default='', max_length=255)),
                ('ebay_url', models.CharField(default='', max_length=255)),
                ('item_sold', models.CharField(default='', max_length=255)),
                ('amazon_url', models.CharField(default='', max_length=255)),
                ('amazon_price_str', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(default='', max_length=25)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=255)),
                ('run_id', models.CharField(default='', max_length=255)),
                ('group_id', models.CharField(default='', max_length=255)),
                ('failure_cause', models.CharField(default='', max_length=255)),
                ('failure_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
