# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayPriceFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_final_value_fee', models.FloatField()),
                ('ebay_listing_fee', models.FloatField()),
                ('paypal_fees_perc', models.FloatField()),
                ('paypal_fees_fixed', models.FloatField()),
                ('perc_margin', models.FloatField()),
                ('fixed_margin', models.FloatField()),
            ],
        ),
    ]
