# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_ebaypriceformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayselleritems',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
