# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20171121_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaysellersearch',
            name='price_str',
            field=models.FloatField(default='-1', max_length=255),
        ),
    ]
