# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20171202_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaysellersearch',
            name='amazon_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
