# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20180108_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbaySellerSearchPendingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default='', max_length=255)),
                ('seller_id', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('price_str', models.FloatField(default='-1', max_length=255)),
                ('ebay_url', models.CharField(default='', max_length=255)),
                ('item_sold', models.CharField(default='', max_length=255)),
                ('amazon_url', models.CharField(default='', max_length=1000)),
                ('amazon_price_str', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
