# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_ebaysellersearchpendingitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaysellersearch',
            name='added_to_pending',
            field=models.BooleanField(default=False),
        ),
    ]
