# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_ebaysellersearch_added_to_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayselleritems',
            name='margin_perc',
            field=models.FloatField(default='0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='ebayselleritems',
            name='minimum_margin',
            field=models.FloatField(default='0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='ebayselleritems',
            name='stock_level',
            field=models.FloatField(default='0.0', max_length=255),
        ),
    ]
