# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20180115_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayselleritems',
            name='margin_perc',
            field=models.FloatField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebayselleritems',
            name='minimum_margin',
            field=models.FloatField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebayselleritems',
            name='stock_level',
            field=models.IntegerField(blank=True),
        ),
    ]
