# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_auto_20180116_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayselleritems',
            name='margin_perc',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ebayselleritems',
            name='minimum_margin',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ebayselleritems',
            name='stock_level',
            field=models.IntegerField(null=True),
        ),
    ]
