# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_auto_20180116_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayselleritems',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
