# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_ebayselleritems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayselleritems',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
