# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_auto_20180118_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayselleritems',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
