# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_auto_20180414_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayproductscsvdata',
            old_name='seller',
            new_name='seller_account',
        ),
        migrations.RenameField(
            model_name='ebayrundetails',
            old_name='seller',
            new_name='seller_account',
        ),
        migrations.AddField(
            model_name='ebayamazonpriceformula',
            name='seller_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ui.SellerTokens'),
            preserve_default=False,
        ),
    ]
