# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_auto_20180420_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbaySellerSearchReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default='', max_length=255)),
                ('seller_id', models.CharField(default='', max_length=255)),
                ('item_found', models.IntegerField(default='-1')),
                ('date_of_search', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='', max_length=255)),
                ('seller_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.SellerTokens')),
            ],
        ),
        migrations.AddField(
            model_name='ebaysellersearch',
            name='search_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.EbaySellerSearchReports'),
        ),
    ]
