# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_auto_20180423_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaysellersearch',
            name='seller_account',
        ),
        migrations.AlterField(
            model_name='ebaysellersearchreports',
            name='item_found',
            field=models.IntegerField(default=0),
        ),
    ]
