# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0025_auto_20180425_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayselleritems',
            name='custom_label',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
