# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0026_auto_20180426_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaypriceformula',
            name='ebay_final_value_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ebaypriceformula',
            name='ebay_listing_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ebaypriceformula',
            name='fixed_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ebaypriceformula',
            name='paypal_fees_fixed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ebaypriceformula',
            name='paypal_fees_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ebaypriceformula',
            name='perc_margin',
            field=models.FloatField(null=True),
        ),
    ]
