# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0028_batchlogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertokens',
            name='is_eligible_for_ebay_update',
            field=models.BooleanField(default=False),
        ),
    ]
