# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0029_sellertokens_is_eligible_for_ebay_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayselleritems',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
