# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0030_auto_20180606_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbaySellerItemsNew',
            fields=[
                ('photo', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('ebay_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('custom_label', models.CharField(default='', max_length=255, null=True)),
                ('price', models.FloatField(default='-1', max_length=255)),
                ('quantity', models.IntegerField(default='-1')),
                ('no_of_times_sold', models.IntegerField(default='-1')),
                ('date_of_listing', models.DateField()),
                ('margin_perc', models.FloatField(max_length=255, null=True)),
                ('minimum_margin', models.FloatField(max_length=255, null=True)),
                ('stock_level', models.IntegerField(null=True)),
                ('status', models.CharField(default='monitored', max_length=255)),
                ('flag', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.SellerTokens')),
            ],
        ),
    ]
