# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0031_ebayselleritemsnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEbayItems',
            fields=[
                ('ebay_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('custom_label', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('no_of_times_sold', models.IntegerField(null=True)),
                ('date_of_listing', models.DateField(null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.SellerTokens')),
            ],
        ),
    ]
