# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0032_tempebayitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempebayitems',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.SellerTokens'),
        ),
    ]
