# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0033_auto_20180619_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertokens',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
