# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_amazonrun_amazonrundetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=255)),
                ('run_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255)),
                ('failure_cause', models.CharField(max_length=255)),
                ('failure_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='amazonrundetails',
            name='group_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazonrundetails',
            name='is_prime',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxy',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
