# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20170923_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayRunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255)),
                ('amazon_url', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('price_str', models.CharField(max_length=20)),
                ('in_stock_str', models.CharField(max_length=10)),
                ('ebay_price', models.CharField(max_length=10)),
                ('ebay_stock', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='amazonrundetails',
            name='ebay_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazonrundetails',
            name='is_ebay_updated',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
