# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20170924_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonrun',
            name='run_finish_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
