# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20170924_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonrun',
            name='run_finish_time',
        ),
    ]
