# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_auto_20171017_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonrundetails',
            name='cause_if_fail',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazonrundetails',
            name='is_eligible_for_ebay_update',
            field=models.BooleanField(default=False),
        ),
    ]
