# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_auto_20171023_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonrundetails',
            name='is_eligible_for_ebay_update',
            field=models.BooleanField(default=True),
        ),
    ]
